language: php

php:
  - 7.4

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - npm install
  - npm run dev
  - php artisan key:generate

cache:
  directories:
    - vendor
    - node_modules
